### ISSUE TITLE
Exiting Firefox while quickcommands popup window is open

### ISSUE THREAD

**Issue by ghost** [victal/quickcommands#8]
Hi,

I've just encountered an issue when exiting Firefox while _quickcommands_ popup windows is open.

When restarting Firefox,
- Firefox window opens at the size of the _quickcommands_ when last opened;
- The _quickcommands_ popup window no longer opens.

I had inadvertently left the quickcommands window opened while checking something elsewhere;
quickcommands (which is not set to be topmost) had been minimized, I forgot it, exited Firefox, and realized the issue above described when I restarted Firefox. 

By the way, having the option to open _quickcommands_ in a tab rather than in a window would maybe be interesting, worthy.

**Comment by victal** [comment]
Hi, 

What OS are you using Firefox with quickcommands on? (and which Window Manager/Desktop Environment, in case you're using it on Linux?) 
I tried it on my Linux machine (with i3wm) and the behaviour was erratic but instead of not opening, the quickcommands window started opening on fullscreen by itself - probably something to do with i3 being a tiling WM.

**Comment by ghost** [comment]
Hi @victal 

I'm running _quickcommands_ 1.2.0 on _Firefox_ 59.0.2 (x64) / _Windows 7SP1_ (x64), I forgot to mention it.

If you experienced a similar issue (though apparently slightly different) on Linux then maybe is the culprit not related to the user's environment.

**Comment by victal** [comment]
Yeah, I don't think the issue is due to the environment as well, but since the symptoms seemed different I thought I'd ask so I can test a fix on both (or similar) environments.

**Comment by victal** [comment]
Hi, I'm still trying out a few fixes regarding the window size problem, but I pushed a bugfix version that should at least fix the add-on window not opening anymore.

**Comment by ghost** [comment]
_quickcommands_ 1.2.1 on Firefox 59.0.2 (x64) / Windows 7SP1 (x64)

I just updated _quickcommands_ to latest version _**1.2.1**_ and indeed, as you mention  it @victal ,
(when exiting Firefox with quickcommands windows opened):

- Firefox window opens at the size of the quickcommands when last opened : **not fixed** (here as well)
- The quickcommands popup window no longer opens : **fixed**

Better!
Thanks for a most appreciated extension.

EDIT: I forgot to mention what seems to be an oddity of little importance, for what it's worth, which occurs with _quickcommands_ version 1.2.1 as it did with previous 1.2.0:

The _quickcommands_ popup window's length increases by 1px each time it is opened, length only, not height. To be sure I perform a screenshot of the window, and the result is (in my case given my window's size preference):
1=1066x600, 2=1067x600, 3-=1068x600 etc...

This is for information only, no idea of a whatever correlation to our above concerns.

**Comment by victal** [comment]
Hello again, 
The main window size problem was worked around on [565636](https://github.com/victal/quickcommands/commit/565636362471e9090d059029fc3e4f63c56e82a7) - the window now closes when focus is lost, which is also the behaviour of the Vivaldi quickcommands window, coincidentally.

The window length bug was fixed on [992b67](https://github.com/victal/quickcommands/commit/992b67fd88bba249da520a068efe4e9ae337a9d7) 

Both fixes should be available on AMO as of version 1.2.2 so I'll be closing this.
